/**
 * The audit ceiling, in the browser.
 *
 * This is a direct transcription of `synthproof/audit/steinke.py`
 * (`max_provable_epsilon` and `canaries_needed_for`), kept to the same two expressions so
 * the calculator on slide 6 cannot drift away from the instrument it describes. The result
 * is checked against `data.ts:ceilingCurve`, which is generated by running the Python.
 *
 * Why this limit exists, in one line: the one-run auditor rejects "this release is eps-DP"
 * only when the adversary's score is too good to be luck. With r guesses, even a PERFECT
 * adversary getting all r right is only alpha-improbable once p^r <= alpha, so the largest
 * epsilon any such test can ever reject is fixed by r alone — before any mechanism is run.
 *
 * Not our result. It follows from the hypothesis test in Steinke, Nasr & Jagielski
 * (NeurIPS 2023, section 7), and the general point that empirical lower bounds are sample-
 * limited goes back at least to Kasiviswanathan & Smith (2014).
 */

export const ALPHA = 0.05

/** Largest epsilon r guesses could EVER certify, at confidence 1 - alpha. Solves p^r = alpha. */
export function maxProvableEpsilon(r: number, alpha: number = ALPHA): number {
  if (r < 1) return 0
  const a = Math.pow(alpha, 1 / r)
  if (a >= 1) return Infinity
  return Math.log(a / (1 - a))
}

/** Canaries needed to certify a given epsilon, assuming an adversary that never errs. */
export function canariesNeededFor(eps: number, alpha: number = ALPHA): number {
  const p = Math.exp(eps) / (1 + Math.exp(eps))
  if (p <= 0 || p >= 1) return Infinity
  return Math.max(1, Math.ceil(Math.log(alpha) / Math.log(p)))
}

/** Formats a canary count that can run to the millions without becoming unreadable. */
export function fmtCount(n: number): string {
  if (!Number.isFinite(n)) return '∞'
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`
  return n.toLocaleString('en-US')
}
