"""Generates `docs/API.md` from the FastAPI app itself.

WHY GENERATED. A hand-written API reference is a second description of the service that drifts
from the first one silently -- which is the failure that put DOMIAS on the certificate's
"not implemented" list for months. This reads the live route table and each handler's own
docstring, so the reference cannot describe an endpoint that does not exist, and cannot miss
one that does.

WHAT IT CANNOT DO. It documents the routes as declared, not the semantics of every field. Where
a handler has no docstring the reference says so rather than inventing a description.

Run from the repository root:

    python scripts/build_api_reference.py
"""

from __future__ import annotations

import inspect
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "API.md"

PREAMBLE = """# API reference

> **Generated by `scripts/build_api_reference.py` from the live route table. Do not edit by
> hand.** Re-run it after adding or changing an endpoint.

The service backs the web console. It is a **research prototype**, and two limits below are
not incidental:

- **Authentication is one shared key.** Set `SYNTHPROOF_API_KEY` and every endpoint that reads
  uploaded data, spends budget or exposes the ledger requires `Authorization: Bearer <key>` or
  `X-API-Key`. It is unset by default so the local demo needs no configuration, and
  `/api/health` reports `auth: "disabled"` loudly when it is. One key means one principal, so
  the ledger's `actor` field cannot distinguish callers, and rotating the key invalidates
  everyone at once. **This is not user authentication.**
- **The service's ledger key lives in memory.** It is generated per process and never
  persisted, so signatures produced here are unverifiable after a restart. That is fine for a
  demo surface and useless as a durable record. The CLI path persists a key:
  `synthproof keygen`, then `run --sign`, then `verify` against the public key.

"""


def routes() -> list[tuple[str, str, str, bool]]:
    """(method, path, docstring, requires_key) for every declared route."""
    from synthproof.api.main import app

    out = []
    for r in app.routes:
        path = getattr(r, "path", None)
        methods = getattr(r, "methods", None)
        endpoint = getattr(r, "endpoint", None)
        if not path or not methods or endpoint is None:
            continue
        if not path.startswith("/api") and path != "/":
            continue
        doc = inspect.getdoc(endpoint) or ""
        # A route is guarded if any of its dependencies is the key check.
        deps = getattr(r, "dependencies", []) or []
        guarded = any("require_api_key" in str(getattr(d, "dependency", d)) for d in deps)
        for m in sorted(methods - {"HEAD", "OPTIONS"}):
            out.append((m, path, doc, guarded))
    return sorted(out, key=lambda x: (x[1], x[0]))


def main() -> None:
    rows = routes()

    parts = [PREAMBLE, "## Endpoints", "", "| Method | Path | Auth |", "|---|---|---|"]
    for method, path, _doc, guarded in rows:
        parts.append(f"| `{method}` | `{path}` | {'key required' if guarded else 'open'} |")
    parts.append("")

    for method, path, doc, guarded in rows:
        parts.append(f"### `{method} {path}`")
        parts.append("")
        parts.append(f"**Auth:** {'shared key required' if guarded else 'open'}")
        parts.append("")
        if doc:
            parts.append(doc)
        else:
            parts.append(
                "*No handler docstring. The behaviour is defined only by the code in "
                "`synthproof/api/main.py` — add a docstring there and re-run this script "
                "rather than describing it here.*"
            )
        parts.append("")

    undocumented = sum(1 for _m, _p, d, _g in rows if not d)
    parts += [
        "---",
        "",
        f"*{len(rows)} routes, {len(rows) - undocumented} with handler docstrings.*",
    ]

    OUT.write_text("\n".join(parts) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} — {len(rows)} routes, {undocumented} undocumented")


if __name__ == "__main__":
    main()
