"""Generates the evidence map for Chapter 5 (Implementation).

WHAT THIS IS AND IS NOT. Chapter 5 describes what was built. Most of its raw material already
exists as module docstrings, defect records and test names -- it is scattered, not missing. This
script gathers it into one place, per section, with live counts and a file:line pointer for
every claim, so writing the chapter is a matter of argument rather than archaeology.

It emits **no prose**. Each section gets its evidence and a `[WRITE: ...]` marker. An unwritten
paragraph stays visibly unwritten.

Counts are read from the tree and from `results/MANIFEST.json` at build time, never typed, and
never defaulted -- `table_h2` in the sibling script once emitted a whole table of zeros from
`.get(key, 0)`, and a chapter that miscounts its own tests is the same defect wearing a
different hat.

Run from the repository root:

    python scripts/build_implementation_evidence.py
"""

from __future__ import annotations

import ast
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "thesis" / "ch05-evidence.md"


def loc(rel: str) -> int:
    return len((ROOT / rel).read_text(encoding="utf-8").split("\n"))


def package_loc() -> int:
    return sum(loc(str(p.relative_to(ROOT))) for p in (ROOT / "synthproof").rglob("*.py"))


def count_tests() -> tuple[int, int]:
    """(test functions, test files). Parsed, not grepped -- a commented-out def is not a test."""
    files = sorted((ROOT / "tests").glob("test_*.py"))
    n = 0
    for f in files:
        for node in ast.walk(ast.parse(f.read_text(encoding="utf-8"))):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and node.name.startswith(
                "test_"
            ):
                n += 1
    return n, len(files)


def module_table() -> str:
    """5.2 -- module boundaries match the pipeline stages in Ch.4."""
    rows = [
        "| Package | Lines | Responsibility | Read first |",
        "|---|---:|---|---|",
    ]
    spec = [
        ("accounting/", "Composition, calibration, discrete noise, the second accountant",
         "`accounting/differential.py`"),
        ("data/", "Public schema, DP domain profiler, the refusal gate, dataset loaders",
         "`data/preflight.py`"),
        ("generators/", "independent · pairwise · aim (private-PGM) · copula · leaky (control)",
         "`generators/aim.py`"),
        ("audit/", "Paired and one-run auditors, subgroup audit, detection floor, TOST",
         "`audit/steinke.py`"),
        ("attacks/", "Distance MIA, exact-match singling out, DOMIAS, attribute inference",
         "`attacks/attribute_inference.py`"),
        ("evaluate/", "TSTR / TRTR on a shared held-out split", "`evaluate/utility.py`"),
        ("ledger/", "Hash-chained Ed25519 ledger, signed head, allocator, sheet signing",
         "`ledger/types.py`"),
        ("frontier/", "Experiment runner, checkpointing, Privacy Data Sheet export",
         "`frontier/experiment.py`"),
        ("api/", "FastAPI service backing the console", "`api/main.py`"),
    ]
    for pkg, what, first in spec:
        pkg_dir = ROOT / "synthproof" / pkg.rstrip("/")
        n = sum(loc(str(q.relative_to(ROOT))) for q in pkg_dir.rglob("*.py"))
        rows.append(f"| `synthproof/{pkg}` | {n:,} | {what} | {first} |")
    return "\n".join(rows)


def main() -> None:
    manifest = json.loads((ROOT / "results" / "MANIFEST.json").read_text(encoding="utf-8"))
    deps = manifest["dependencies"]
    env = manifest["environment"]
    n_tests, n_files = count_tests()

    dep_rows = "\n".join(
        f"| `{name}` | {ver} | {why} |"
        for name, ver, why in [
            ("dp-accounting", deps["dp-accounting"],
             "Composition. **Delegated, never re-derived** — standing rule 1. Our own RDP "
             "subsampling bound under-reported ε by ~2× at q=0.01 (audit finding F4)."),
            ("mbi", deps["mbi"],
             "private-PGM. Real graphical-model inference behind AIM; requires Python ≥ 3.11."),
            ("autodp", deps["autodp"],
             "The **second** accountant. Cross-checks every release; verdict ships in the "
             "signed payload (`accounting/differential.py`)."),
            ("scipy", deps["scipy"], "Exact binomial intervals, χ² goodness-of-fit, bootstrap."),
            ("numpy", deps["numpy"], "Sampling and array work."),
            ("pandas", deps["pandas"], "Tabular representation."),
            ("scikit-learn", deps["scikit-learn"], "TSTR / TRTR downstream classifiers."),
        ]
    )

    parts = [
        "# Chapter 5 — evidence map",
        "",
        "> **Generated by `scripts/build_implementation_evidence.py`. Do not edit by hand.**",
        "> Counts are read from the tree and `results/MANIFEST.json` at build time. The prose is",
        "> the author's and is deliberately not generated.",
        "",
        f"> Environment of record: **Python {env['python']}**, {env['platform']}, "
        f"commit `{manifest['git']['commit'][:7]}`.",
        "",
        "---",
        "",
        "## 5.1 Technology choices (~250 words)",
        "",
        "| Dependency | Version | Why this one |",
        "|---|---|---|",
        dep_rows,
        "",
        "[WRITE: ~250 words. The through-line is that **the interesting choices are the ones "
        "where we chose NOT to implement something.** Composition is delegated because our "
        "hand-rolled version was wrong by 2×; a second accountant exists because Cebere et al. "
        "found 13 guarantee violations across 12 DP libraries; SQLite rather than a database "
        "tier because the ledger is a single-writer append log. Python 3.11 is forced by "
        "private-pgm, and that is worth one sentence because it gated real AIM.]",
        "",
        "---",
        "",
        "## 5.2 Package structure (~200 words)",
        "",
        module_table(),
        "",
        f"*Package total: **{package_loc():,} lines**. Tests: **{n_tests} test functions "
        f"across {n_files} files**.*",
        "",
        "> ⚠️ **Two different test counts exist and they are both correct.** This is the count "
        "of test *functions*; `pytest` reports a larger number of test *cases*, because "
        "`@parametrize` expands one function into many. Quote whichever you mean and say which "
        "it is — writing 'N tests' for the function count next to a CI badge showing the case "
        "count is the kind of small inconsistency an examiner notices.",
        "",
        "[WRITE: ~200 words. The observation worth making: `audit/` is larger than "
        "`generators/`. For a synthesis project that inversion is unusual and it is the "
        "structural evidence that the measurement, not the mechanism, is the subject.]",
        "",
        "---",
        "",
        "## 5.3 Noise sampling (~300 words)",
        "",
        "| Claim | Evidence |",
        "|---|---|",
        "| Discrete Gaussian by rejection sampling, CKS'20 §5.2 Alg. 1 | "
        "`accounting/noise.py::_discrete_gaussian_single` |",
        "| Discrete Laplace as a two-sided geometric | Ghosh, Roughgarden & Sundararajan (2012) |",
        "| Why discrete at all | Mironov (2012): inverse-CDF float sampling leaks through "
        "low-order bits. Rounding a continuous Gaussian does **not** give a discrete one |",
        "| The sampler is validated, not asserted | χ² goodness-of-fit against the exact PMF, "
        "`tests/test_accounting.py:99` — tails folded so no expected bin is too small |",
        "",
        "**The defect to report, and it is the best paragraph in this section.** A previous "
        "version returned a deterministic zero vector for σ < 0.3. The accountant still charged "
        "a finite ε. So the release paid budget *and* leaked deterministically — worse than not "
        "paying at all, which is why it became standing rule 3. The fix is a refusal to "
        "special-case: `accounting/noise.py:133` now carries a comment explaining that the "
        "rejection sampler is valid for every σ > 0 and concentrates on 0 for small σ *by "
        "sampling rather than by fiat*.",
        "",
        "[WRITE: ~300 words. Lead with why discrete, then the validation, then the defect. The "
        "defect is the point: a one-line shortcut voided the guarantee silently and no test "
        "would have caught it without a distributional check.]",
        "",
        "---",
        "",
        "## 5.4 Calibration implementation (~250 words)",
        "",
        "| Claim | Evidence |",
        "|---|---|",
        "| Bracket-and-bisect inversion of the composition theorem | "
        "`accounting/calibration.py::calibrate_noise_scale` |",
        "| Budget split routed through one implementation | `calibration.py:160` calls "
        "`Allocator.allocate_weighted` |",
        "| Never overspends | proved/target ≤ 1 across the whole grid — see "
        "`ch07-tables.md` §7.1 |",
        "| CI-gated | across 24 configurations |",
        "",
        "**The motivating failure:** before calibration, `noise_scale = sqrt(num_columns) / "
        "target_eps` was set by hand and a target of **8.0 composed to 70.49** (audit finding "
        "F2). Every step was individually sound; the number the operator typed simply did not "
        "mean what they thought.",
        "",
        "[WRITE: ~250 words. The general claim worth making: a system can satisfy the DP "
        "definition while its interface deceives its operator. Song et al. (CSCW 2024) found "
        "practitioners do not verify DP guarantees, which is what makes that class of failure "
        "durable. Cross-reference Ch.4 §4.4 rather than repeating the result.]",
        "",
        "---",
        "",
        "## 5.5 Ledger implementation (~250 words)",
        "",
        "| Claim | Evidence |",
        "|---|---|",
        "| Canonical bytes: sorted keys, fixed-precision floats | "
        "`ledger/types.py::canonical_bytes` — `%.8f` for ε and sensitivity, `%.8e` for δ |",
        "| Why fixed precision | float repr varies; without it a signature is not reproducible "
        "and verification fails on a byte-identical record |",
        "| Chain + signature | SHA-256 over canonical bytes, Ed25519 over the payload |",
        "| Attacks run against **live SQLite**, not the API | `tests/test_ledger_adversarial.py` |",
        "",
        "**Chaining alone is not enough, and this is the finding.** A hash chain detects "
        "modification, insertion and reordering but **not truncation** — a shortened chain is "
        "internally consistent. Deleting the last two entries left `verify()` returning `True`, "
        "so an operator could remove exactly the entries recording a budget overspend. A signed "
        "`ledger_head` committing to `(entry_count, tip_hash)` closes it: **9 distinct attacks "
        "stopped, up from 8**, across 14 tests.",
        "",
        "[WRITE: ~250 words. Do not call the ledger 'append-only' — nothing prevents an append; "
        "what is detectable is that one happened. State plainly that it does not stop an "
        "adversary holding the signing key, and that one shared API key means the `actor` field "
        "cannot identify who spent the budget.]",
        "",
        "---",
        "",
        "## 5.6 Testing and CI (~250 words)",
        "",
        "| Claim | Evidence |",
        "|---|---|",
        f"| Suite size | **{n_tests} test functions across {n_files} files** "
        f"(more cases than that after `@parametrize` expansion — run `make test` for the "
        f"figure to quote) |",
        "| Property-based testing | Hypothesis, `tests/test_accounting_properties.py` |",
        "| Differential test against a second accountant | same file, promoted to a **release "
        "gate** in `accounting/differential.py` |",
        "| Adversarial ledger tests | 9 attacks / 14 tests against live SQLite |",
        "| Console | 10 vitest tests, incl. an SSE frame split across two network chunks |",
        "| Every self-audit defect has a named regression test | verified by **reintroducing "
        "the bug**, not by reading the test |",
        "",
        "[WRITE: ~250 words. The argument: a test verified by reading is not evidence. Both "
        "defects found by the 2026-08-16 adversarial audit sat behind confident comments "
        "claiming the opposite. Note that two of the twelve defects were caught by *controls* "
        "rather than by reading code, which is why every new measurement now ships with a "
        "positive and a negative control.]",
        "",
        "---",
        "",
        "## Figures for this chapter",
        "",
        "- **`figures/fig-discrete-gaussian.png`** — sampled counts against the exact PMF at "
        "σ = 1 and σ = 3, with the χ² p-value in each panel. Generated by `make figures` from "
        "the sampler that ships, so it is a measurement of the code rather than an "
        "illustration of the idea.",
        "- Coverage report",
        "",
    ]

    OUT.write_text("\n".join(parts) + "\n", encoding="utf-8")
    body = "\n".join(parts)
    print(f"wrote {OUT.relative_to(ROOT)}")
    print(f"  {len(body.split())} words of evidence, {body.count('[WRITE:')} sections to write")


if __name__ == "__main__":
    main()
