"""Before/after table for the research/27 fixes: pre-fix grids vs the audit27 re-run.

    python -m scripts.compare_audit27            # prints markdown, writes research/28_audit27_results.md

Reads the archived pre-fix aggregates (results/archive_pre_audit27/) and the re-run aggregates
(results/full/*_h1_full.json). Every number is a 5-seed mean at the best epsilon, computed here
from the committed files -- nothing is typed in.
"""

import json
import math
from pathlib import Path

from scripts._cells import seed_mean_cells

DATASETS = ["adult", "bank", "texas", "fire", "wine", "acs", "diabetes", "bcw", "german", "mushroom", "nursery"]
OLD_SMALL = {"german", "wine", "bcw", "mushroom", "nursery"}
ARCH = Path("results/archive_pre_audit27")
NEW = Path("results/full")


def _load(p: Path):
    if not p.exists():
        return None
    return json.loads(p.read_text(encoding="utf-8").replace("NaN", "null"))


def _get(c, k):
    v = c.get(k)
    if isinstance(v, dict):
        v = v.get("mean")
    return v if isinstance(v, (int, float)) and not (isinstance(v, float) and math.isnan(v)) else None


def summarise(payload):
    cells = seed_mean_cells(payload["cells"])
    by = {}
    for c in cells:
        by.setdefault(c["mechanism"], []).append(c)
    trtr = [(_get(c, "trtr_f1"), c) for c in cells if _get(c, "trtr_f1")]
    t = sum(v for v, _ in trtr) / len(trtr)

    def best(mech, key="tstr_f1", ratio=True, low=False):
        vals = [_get(c, key) for c in by.get(mech, [])]
        vals = [v for v in vals if v is not None]
        if not vals:
            return None
        v = min(vals) if low else max(vals)
        return 100 * v / t if ratio else v

    out = {m: best(m) for m in ("independent", "pairwise", "aim", "mst")}
    out["ours"] = max(v for v in (out["aim"], out["mst"]) if v is not None)
    out["base"] = max(v for v in (out["independent"], out["pairwise"]) if v is not None)
    out["multi_ours"] = max(
        (v for v in (best("aim", "usefulness_multi", False), best("mst", "usefulness_multi", False)) if v is not None),
        default=None,
    )
    out["struct_ours"] = min(
        (v for v in (best("aim", "structure_error_all", False, True), best("mst", "structure_error_all", False, True)) if v is not None),
        default=None,
    )
    out["struct_base"] = min(
        (v for v in (best("independent", "structure_error_all", False, True), best("pairwise", "structure_error_all", False, True)) if v is not None),
        default=None,
    )
    out["tvd_ours"] = min(
        (v for v in (best("aim", "pair_tvd", False, True), best("mst", "pair_tvd", False, True)) if v is not None),
        default=None,
    )
    out["tvd_base"] = min(
        (v for v in (best("independent", "pair_tvd", False, True), best("pairwise", "pair_tvd", False, True)) if v is not None),
        default=None,
    )
    proved = [(_get(c, "target_eps") or c["target_eps"], _get(c, "proved_eps")) for c in by.get("aim", [])]
    out["aim_proved_at_8"] = next((p for e, p in proved if e == 8.0), None)
    return out


def fmt(v, pct=True, nd=3):
    if v is None:
        return "—"
    return f"{v:.0f}%" if pct else f"{v:.{nd}f}"


def main():
    rows = []
    for d in DATASETS:
        old_p = ARCH / (f"{d}_h1_all_families.json" if d in OLD_SMALL else f"{d}_h1_full.json")
        old, new = _load(old_p), _load(NEW / f"{d}_h1_full.json")
        o = summarise(old) if old else None
        n = summarise(new) if new else None
        rows.append((d, o, n))

    lines = [
        "# 28 — audit27 re-run: before vs after the research/27 fixes",
        "",
        "Generated by `scripts/compare_audit27.py` from committed files. 5-seed means, best ε, every row.",
        "Usefulness = TSTR ÷ TRTR (random forest; after the fix scored on rows the generator never saw).",
        "'3-model' = mean over random forest, logistic regression and gradient boosting. Structure = mean",
        "association error over EVERY column pair; 2-way TVD = mean total-variation distance over every",
        "2-way marginal (both lower = better, new metrics, so no 'before').",
        "",
        "| Dataset | Ours before | Ours after | Baseline after | 3-model after | AIM proved ε at target 8 | Structure ours / base | 2-way TVD ours / base |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for d, o, n in rows:
        if n is None:
            lines.append(f"| {d} | {fmt(o['ours']) if o else '—'} | running | | | | | |")
            continue
        lines.append(
            f"| {d} | {fmt(o['ours']) if o else '—'} | **{fmt(n['ours'])}** | {fmt(n['base'])} | "
            f"{fmt(100 * n['multi_ours']) if n['multi_ours'] else '—'} | {fmt(n['aim_proved_at_8'], False, 3)} "
            f"(before {fmt(o['aim_proved_at_8'], False, 3) if o else '—'}) | "
            f"{fmt(n['struct_ours'], False)} / {fmt(n['struct_base'], False)} | {fmt(n['tvd_ours'], False)} / {fmt(n['tvd_base'], False)} |"
        )
    text = "\n".join(lines) + "\n"
    print(text)
    Path("research/28_audit27_results.md").write_text(text, encoding="utf-8")


if __name__ == "__main__":
    main()
