"""Regenerates every published number and emits a manifest that pins it.

WHAT THIS BUYS. The thesis can state "every number in this document was regenerated by commit
X under manifest hash Y" — a claim very few undergraduate theses can make, and one a reviewer
can check. It also catches the failure mode where a result file drifts from the code that
supposedly produced it, which is otherwise invisible until someone tries to rerun an
experiment months later.

WHAT THE MANIFEST COVERS. The commit, whether the tree was dirty, the interpreter and platform,
resolved versions of every dependency that affects a number, the dataset checksums, the seeds
and grids each experiment used, and a SHA-256 over each result file plus one over all of them
together. Two runs that agree on the manifest hash produced identical results.

WHAT IT DOES NOT COVER, stated so nobody over-reads it: floating-point results can differ
across BLAS builds and CPU architectures even at a fixed seed. A manifest mismatch means
"something changed", not necessarily "someone edited a number".

AND `--run` DOES NOT RECOMPUTE H1. `run_h1` is resumable by design -- `frontier/checkpoint.py`
exists because the 75-cell grid was lost twice mid-run -- so it reloads `results/h1_cells/` and
re-aggregates rather than re-fitting. The tell is `elapsed_seconds`: H1 reports ~0.7s where H2,
H3 and fairness report 20-70s. Those three genuinely re-run. To force H1 to recompute, delete
`results/h1_cells/` first, and expect roughly four hours per dataset. Verified 2026-08-23: a
`--update` pass reproduced every committed number exactly, with only timing metadata changing --
which is a real reproducibility result for H2/H3/fairness and a checkpoint-integrity result for
H1, and those are different claims.

Usage:
    python -m scripts.reproduce              # verify against the committed manifest
    python -m scripts.reproduce --run        # re-run every experiment first (long)
    python -m scripts.reproduce --update     # re-run and rewrite the manifest
"""

import argparse
import hashlib
import json
import platform
import subprocess
import sys
from datetime import datetime, timezone
from importlib.metadata import PackageNotFoundError, version
from pathlib import Path
from typing import Dict, List, Optional

MANIFEST_PATH = Path("results/MANIFEST.json")

# Every file whose contents a published claim depends on.
RESULT_FILES = [
    "results/h1_all_families.json",
    "results/acs/h1_all_families.json",
    "results/h2_subgroups.json",
    "results/h2_analysis.json",
    "results/acs/h2_subgroups.json",
    "results/acs/h2_analysis.json",
    "results/h3_allocation.json",
    "results/acs/h3_allocation.json",
    "results/detection_floor.json",
    # Added 2026-08-23 with M2.11. A result file outside this list is a published number that
    # `make reproduce` cannot vouch for, which is the drift the manifest exists to catch.
    "results/fairness.json",
    "results/acs/fairness.json",
    # Added 2026-08-25. Verified bit-reproducible by running it twice and diffing every field
    # except `elapsed_seconds`.
    "results/gdp_audit.json",
]

# DELIBERATELY NOT PINNED, and this is a limitation rather than an oversight.
#
#   results/clique_confound.json          uses `aim`
#   results/acs/clique_confound.json      uses `aim`
#   results/selection_ablation.json       uses `fixed_workload` (an AIM subclass)
#   results/acs/selection_ablation.json   uses `fixed_workload`
#
# `mbi`'s `synthetic_data` draws from unseeded randomness, so calling `generate` twice on the
# SAME fitted model returns different tables -- confirmed directly, and pinned as a test in
# `tests/test_fixed_workload.py::test_sampling_is_NOT_reproducible_and_that_is_recorded`.
# Any AIM-family result is therefore reproducible in DISTRIBUTION but not BIT-IDENTICAL, and
# adding these files would make `make reproduce` fail on every clean re-run -- which would
# train everyone to ignore it.
#
# The honest consequence, which ch06 s6.6 must state: the reproducibility claim covers the
# marginal-based and DP-SGD results in RESULT_FILES, and does NOT extend to the AIM-family
# numbers. Fixing it needs a seeded sampler in `mbi`, not a change here.
UNPINNED_AIM_FAMILY = [
    "results/clique_confound.json",
    "results/acs/clique_confound.json",
    "results/selection_ablation.json",
    "results/acs/selection_ablation.json",
]

# The experiments that produce them, in dependency order.
EXPERIMENTS = [
    ("h1_adult", [sys.executable, "-m", "scripts.run_h1"]),
    ("h1_acs", [sys.executable, "-m", "scripts.run_h1", "--dataset", "acs"]),
    ("h2_adult", [sys.executable, "-m", "scripts.run_h2"]),
    ("h2_acs", [sys.executable, "-m", "scripts.run_h2", "--dataset", "acs"]),
    ("h2_analysis_adult", [sys.executable, "-m", "scripts.analyse_h2"]),
    ("h2_analysis_acs", [sys.executable, "-m", "scripts.analyse_h2", "--dataset", "acs"]),
    ("h3_adult", [sys.executable, "-m", "scripts.run_h3"]),
    ("h3_acs", [sys.executable, "-m", "scripts.run_h3", "--dataset", "acs"]),
    ("detection_floor", [sys.executable, "-m", "scripts.run_detection_floor"]),
    ("fairness_adult", [sys.executable, "-m", "scripts.run_fairness"]),
    ("fairness_acs", [sys.executable, "-m", "scripts.run_fairness", "--dataset", "acs"]),
    # 5,000 fits on an 11-record worst-case instance; ~5 minutes.
    ("gdp_audit", [sys.executable, "-m", "scripts.run_gdp_audit", "--runs", "2500"]),
]

# Only packages whose version can change a number. Formatters and linters cannot, so listing
# them would make the manifest churn without meaning.
NUMERIC_DEPENDENCIES = [
    "numpy",
    "pandas",
    "scipy",
    "scikit-learn",
    "dp-accounting",
    "mbi",
    "autodp",
]


# Fields that record how long a run took, not what it produced. Hashing them makes the
# manifest unstable by construction: two identical re-runs differ only in wall-clock timing,
# so `make reproduce` reports DIVERGED even when every number is bit-identical. Observed
# doing exactly that — three consecutive clean re-runs produced three different manifest
# hashes, with `elapsed_seconds` the only differing field.
#
# Anything added here must be metadata a reproducer would NOT expect to match. Do not add a
# field to silence a mismatch that reflects a real change in a result.
NON_DETERMINISTIC_KEYS = frozenset({"elapsed_seconds"})


def _canonical_bytes(path: Path) -> bytes:
    """Bytes to hash for a result file, with timing metadata stripped.

    JSON result files are re-serialised with the non-deterministic keys removed and keys
    sorted, so the hash tracks the RESULT rather than the run. Non-JSON files, and JSON that
    fails to parse, are hashed verbatim — a file we cannot interpret is not one to normalise.
    """
    raw = path.read_bytes()
    if path.suffix != ".json":
        return raw
    try:
        payload = json.loads(raw.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError):
        return raw
    if isinstance(payload, dict):
        payload = {k: v for k, v in payload.items() if k not in NON_DETERMINISTIC_KEYS}
    return json.dumps(payload, sort_keys=True, separators=(",", ":")).encode("utf-8")


def _sha256(path: Path) -> Optional[str]:
    if not path.exists():
        return None
    return hashlib.sha256(_canonical_bytes(path)).hexdigest()


def _git(*args: str) -> str:
    try:
        return subprocess.run(
            ["git", *args], capture_output=True, text=True, check=True
        ).stdout.strip()
    except Exception:
        return "unknown"


def _versions() -> Dict[str, str]:
    out = {}
    for pkg in NUMERIC_DEPENDENCIES:
        try:
            out[pkg] = version(pkg)
        except PackageNotFoundError:
            out[pkg] = "not installed"
    return out


def _experiment_config() -> Dict[str, dict]:
    """Reads each runner's grid from the module itself, so the manifest cannot drift from it."""
    cfg: Dict[str, dict] = {}
    try:
        from scripts import run_h1

        # One runner drives both datasets, so the grid is shared and only the per-dataset
        # target column and structure pair differ.
        cfg["h1"] = {
            "n_rows": run_h1.N_ROWS,
            "eps_grid": list(run_h1.EPS_GRID),
            "seeds": list(run_h1.SEEDS),
            "datasets": {
                k: {"target_col": v["target_col"], "corr_cols": list(v["corr_cols"])}
                for k, v in run_h1.DATASETS.items()
            },
        }
    except Exception as exc:
        cfg["h1"] = {"error": str(exc)}
    try:
        from scripts import run_h2

        cfg["h2"] = {
            "n_rows": run_h2.N_ROWS,
            "eps_grid": list(run_h2.EPS_GRID),
            "seeds": list(run_h2.SEEDS),
            "mechanism": run_h2.MECHANISM,
            "total_canaries": run_h2.TOTAL_CANARIES,
            # Per-dataset since the runner was parameterised. Reading the removed module-level
            # ATTRIBUTES constant here raised, and the broad `except` wrote the AttributeError
            # into the manifest in place of the grid — pinning an error message rather than a
            # configuration. `tests/test_reproduce.py` now asserts no section carries an error.
            "attributes": {k: list(v["attributes"]) for k, v in run_h2.DATASETS.items()},
        }
    except Exception as exc:
        cfg["h2"] = {"error": str(exc)}
    try:
        from scripts import run_detection_floor as rdf

        cfg["detection_floor"] = {
            "n_rows": rdf.N_ROWS,
            "canary_counts": list(rdf.CANARY_COUNTS),
            "leak_fractions": list(rdf.LEAK_FRACTIONS),
            "seeds": list(rdf.SEEDS),
        }
    except Exception as exc:
        cfg["detection_floor"] = {"error": str(exc)}
    try:
        from scripts import run_h3

        cfg["h3"] = {
            "n_rows": run_h3.N_ROWS,
            "eps_grid": list(run_h3.EPS_GRID),
            "seeds": list(run_h3.SEEDS),
            "priority_weight": run_h3.PRIORITY_WEIGHT,
            "weights_source": "declared-public",
            "datasets": {
                k: {"target_col": v["target_col"], "priority_cols": list(v["priority_cols"])}
                for k, v in run_h3.DATASETS.items()
            },
        }
    except Exception as exc:
        cfg["h3"] = {"error": str(exc)}
    return cfg


def build_manifest() -> dict:
    """Collects everything needed to decide whether two runs agree."""
    files = {p: _sha256(Path(p)) for p in RESULT_FILES}

    # One hash over all result files, so a single value identifies the whole result set.
    combined = hashlib.sha256()
    for name in sorted(files):
        combined.update(name.encode())
        combined.update((files[name] or "MISSING").encode())

    return {
        "manifest_version": 1,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "git": {
            "commit": _git("rev-parse", "HEAD"),
            "branch": _git("rev-parse", "--abbrev-ref", "HEAD"),
            # A dirty tree means the commit does not describe what actually ran.
            "dirty": bool(_git("status", "--porcelain")),
        },
        "environment": {
            "python": sys.version.split()[0],
            "platform": platform.platform(),
            "machine": platform.machine(),
        },
        "dependencies": _versions(),
        "datasets": {"adult_sha256": _read_checksum("adult.zip")},
        "experiments": _experiment_config(),
        "files": files,
        "manifest_hash": combined.hexdigest(),
    }


def _read_checksum(filename: str) -> Optional[str]:
    path = Path("data/CHECKSUMS.txt")
    if not path.exists():
        return None
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.strip().startswith("#") or not line.strip():
            continue
        parts = line.split()
        if len(parts) >= 2 and parts[1] == filename:
            return parts[0]
    return None


def run_experiments() -> List[str]:
    """Re-runs every experiment. Returns the names that failed."""
    failed = []
    for name, cmd in EXPERIMENTS:
        print(f"\n{'=' * 70}\n  running {name}\n{'=' * 70}", flush=True)
        result = subprocess.run(cmd)
        if result.returncode != 0:
            print(f"  {name} FAILED (exit {result.returncode})")
            failed.append(name)
    return failed


def compare(current: dict, committed: dict) -> List[str]:
    """Differences that matter. Timestamps and paths are ignored deliberately."""
    diffs = []
    if current["manifest_hash"] != committed.get("manifest_hash"):
        diffs.append(
            f"manifest hash: {committed.get('manifest_hash', 'none')[:16]}... -> "
            f"{current['manifest_hash'][:16]}..."
        )
    for name, digest in current["files"].items():
        old = committed.get("files", {}).get(name)
        if digest != old:
            if old is None:
                diffs.append(f"{name}: not in committed manifest")
            elif digest is None:
                diffs.append(f"{name}: MISSING (was {old[:12]}...)")
            else:
                diffs.append(f"{name}: {old[:12]}... -> {digest[:12]}...")
    for pkg, ver in current["dependencies"].items():
        old = committed.get("dependencies", {}).get(pkg)
        if old is not None and old != ver:
            diffs.append(f"dependency {pkg}: {old} -> {ver}")
    return diffs


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--run", action="store_true", help="Re-run every experiment first (long)")
    ap.add_argument("--update", action="store_true", help="Re-run and rewrite the manifest")
    ap.add_argument(
        "--rehash",
        action="store_true",
        help=(
            "Rewrite the manifest from the results ALREADY on disk, without re-running "
            "anything. Refuses unless every currently-pinned file still matches, so it can "
            "only ever ADD a file, never paper over a changed number."
        ),
    )
    args = ap.parse_args()

    if args.run or args.update:
        failed = run_experiments()
        if failed:
            raise SystemExit(
                f"\nExperiments failed: {', '.join(failed)}. "
                "Not writing a manifest for a partial run."
            )

    manifest = build_manifest()

    if args.rehash:
        # --rehash exists to pin a NEWLY ADDED result file after a clean verify pass. It must
        # never be usable to silence a real divergence, so every file that was already pinned
        # has to still match before anything is written.
        committed = (
            json.loads(MANIFEST_PATH.read_text(encoding="utf-8")) if MANIFEST_PATH.exists() else {}
        )
        old_files = committed.get("files", {})
        new_files = manifest.get("files", {})
        changed = [f for f, h in old_files.items() if f in new_files and new_files[f] != h]
        if changed:
            raise SystemExit(
                "\n  REFUSING to rehash: these already-pinned results have CHANGED:\n    "
                + "\n    ".join(changed)
                + "\n\n  --rehash may only ADD files after a clean verify. A changed number "
                "needs\n  `--update`, and a human deciding the new value is correct."
            )
        added = sorted(set(new_files) - set(old_files))
        MANIFEST_PATH.parent.mkdir(parents=True, exist_ok=True)
        MANIFEST_PATH.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
        print(f"\n  rehashed {MANIFEST_PATH}")
        for f in added:
            print(f"    + pinned {f}")
        if not added:
            print("    (no new files; only the manifest hash was refreshed)")
        return

    print(f"\n{'=' * 70}\n  MANIFEST\n{'=' * 70}")
    print(
        f"  commit       {manifest['git']['commit'][:12]}"
        f"{'  (DIRTY TREE)' if manifest['git']['dirty'] else ''}"
    )
    print(
        f"  python       {manifest['environment']['python']}  "
        f"{manifest['environment']['machine']}"
    )
    for name, digest in manifest["files"].items():
        print(f"  {name:<38} {digest[:16] + '...' if digest else 'MISSING'}")
    print(f"\n  manifest hash  {manifest['manifest_hash']}")

    if manifest["git"]["dirty"]:
        print(
            "\n  WARNING: the working tree is dirty, so the commit above does not "
            "describe what ran."
        )

    missing = [n for n, d in manifest["files"].items() if d is None]
    if missing:
        print(f"\n  {len(missing)} result file(s) missing. Run with --run to generate them.")

    if args.update:
        MANIFEST_PATH.parent.mkdir(parents=True, exist_ok=True)
        MANIFEST_PATH.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
        print(f"\n  wrote {MANIFEST_PATH}")
        return

    if not MANIFEST_PATH.exists():
        print(
            f"\n  No committed manifest at {MANIFEST_PATH}. "
            "Create one with --update once the results are final."
        )
        return

    committed = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    diffs = compare(manifest, committed)

    if not diffs:
        print("\n  REPRODUCED: every result file matches the committed manifest.")
        return

    print(f"\n  DIVERGED from the committed manifest ({len(diffs)}):")
    for d in diffs:
        print(f"    - {d}")
    print(
        "\n  Note that floating-point results can differ across BLAS builds and CPU\n"
        "  architectures even at a fixed seed. A mismatch means something changed, not\n"
        "  necessarily that a number was edited."
    )
    raise SystemExit(1)


if __name__ == "__main__":
    main()
