"""Regenerates every published number and emits a manifest that pins it.

WHAT THIS BUYS. The thesis can state "every number in this document was regenerated by commit
X under manifest hash Y" — a claim very few undergraduate theses can make, and one a reviewer
can check. It also catches the failure mode where a result file drifts from the code that
supposedly produced it, which is otherwise invisible until someone tries to rerun an
experiment months later.

WHAT THE MANIFEST COVERS. The commit, whether the tree was dirty, the interpreter and platform,
resolved versions of every dependency that affects a number, the dataset checksums, the seeds
and grids each experiment used, and a SHA-256 over each result file plus one over all of them
together. Two runs that agree on the manifest hash produced identical results.

WHAT IT DOES NOT COVER, stated so nobody over-reads it: floating-point results can differ
across BLAS builds and CPU architectures even at a fixed seed. A manifest mismatch means
"something changed", not necessarily "someone edited a number".

Usage:
    python -m scripts.reproduce              # verify against the committed manifest
    python -m scripts.reproduce --run        # re-run every experiment first (long)
    python -m scripts.reproduce --update     # re-run and rewrite the manifest
"""

import argparse
import hashlib
import json
import platform
import subprocess
import sys
from datetime import datetime, timezone
from importlib.metadata import PackageNotFoundError, version
from pathlib import Path
from typing import Dict, List, Optional

MANIFEST_PATH = Path("results/MANIFEST.json")

# Every file whose contents a published claim depends on.
RESULT_FILES = [
    "results/h1_all_families.json",
    "results/h2_subgroups.json",
    "results/detection_floor.json",
]

# The experiments that produce them, in dependency order.
EXPERIMENTS = [
    ("h1", [sys.executable, "-m", "scripts.run_h1"]),
    ("h2", [sys.executable, "-m", "scripts.run_h2"]),
    ("detection_floor", [sys.executable, "-m", "scripts.run_detection_floor"]),
]

# Only packages whose version can change a number. Formatters and linters cannot, so listing
# them would make the manifest churn without meaning.
NUMERIC_DEPENDENCIES = [
    "numpy", "pandas", "scipy", "scikit-learn", "dp-accounting", "mbi", "autodp",
]


def _sha256(path: Path) -> Optional[str]:
    if not path.exists():
        return None
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def _git(*args: str) -> str:
    try:
        return subprocess.run(["git", *args], capture_output=True, text=True,
                              check=True).stdout.strip()
    except Exception:
        return "unknown"


def _versions() -> Dict[str, str]:
    out = {}
    for pkg in NUMERIC_DEPENDENCIES:
        try:
            out[pkg] = version(pkg)
        except PackageNotFoundError:
            out[pkg] = "not installed"
    return out


def _experiment_config() -> Dict[str, dict]:
    """Reads each runner's grid from the module itself, so the manifest cannot drift from it."""
    cfg: Dict[str, dict] = {}
    try:
        from scripts import run_h1
        cfg["h1"] = {"n_rows": run_h1.N_ROWS, "eps_grid": list(run_h1.EPS_GRID),
                     "seeds": list(run_h1.SEEDS), "target_col": run_h1.TARGET_COL}
    except Exception as exc:
        cfg["h1"] = {"error": str(exc)}
    try:
        from scripts import run_h2
        cfg["h2"] = {"n_rows": run_h2.N_ROWS, "eps_grid": list(run_h2.EPS_GRID),
                     "seeds": list(run_h2.SEEDS), "attributes": list(run_h2.ATTRIBUTES),
                     "total_canaries": run_h2.TOTAL_CANARIES}
    except Exception as exc:
        cfg["h2"] = {"error": str(exc)}
    try:
        from scripts import run_detection_floor as rdf
        cfg["detection_floor"] = {"n_rows": rdf.N_ROWS,
                                  "canary_counts": list(rdf.CANARY_COUNTS),
                                  "leak_fractions": list(rdf.LEAK_FRACTIONS),
                                  "seeds": list(rdf.SEEDS)}
    except Exception as exc:
        cfg["detection_floor"] = {"error": str(exc)}
    return cfg


def build_manifest() -> dict:
    """Collects everything needed to decide whether two runs agree."""
    files = {p: _sha256(Path(p)) for p in RESULT_FILES}

    # One hash over all result files, so a single value identifies the whole result set.
    combined = hashlib.sha256()
    for name in sorted(files):
        combined.update(name.encode())
        combined.update((files[name] or "MISSING").encode())

    return {
        "manifest_version": 1,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "git": {
            "commit": _git("rev-parse", "HEAD"),
            "branch": _git("rev-parse", "--abbrev-ref", "HEAD"),
            # A dirty tree means the commit does not describe what actually ran.
            "dirty": bool(_git("status", "--porcelain")),
        },
        "environment": {
            "python": sys.version.split()[0],
            "platform": platform.platform(),
            "machine": platform.machine(),
        },
        "dependencies": _versions(),
        "datasets": {"adult_sha256": _read_checksum("adult.zip")},
        "experiments": _experiment_config(),
        "files": files,
        "manifest_hash": combined.hexdigest(),
    }


def _read_checksum(filename: str) -> Optional[str]:
    path = Path("data/CHECKSUMS.txt")
    if not path.exists():
        return None
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.strip().startswith("#") or not line.strip():
            continue
        parts = line.split()
        if len(parts) >= 2 and parts[1] == filename:
            return parts[0]
    return None


def run_experiments() -> List[str]:
    """Re-runs every experiment. Returns the names that failed."""
    failed = []
    for name, cmd in EXPERIMENTS:
        print(f"\n{'=' * 70}\n  running {name}\n{'=' * 70}", flush=True)
        result = subprocess.run(cmd)
        if result.returncode != 0:
            print(f"  {name} FAILED (exit {result.returncode})")
            failed.append(name)
    return failed


def compare(current: dict, committed: dict) -> List[str]:
    """Differences that matter. Timestamps and paths are ignored deliberately."""
    diffs = []
    if current["manifest_hash"] != committed.get("manifest_hash"):
        diffs.append(
            f"manifest hash: {committed.get('manifest_hash', 'none')[:16]}... -> "
            f"{current['manifest_hash'][:16]}..."
        )
    for name, digest in current["files"].items():
        old = committed.get("files", {}).get(name)
        if digest != old:
            if old is None:
                diffs.append(f"{name}: not in committed manifest")
            elif digest is None:
                diffs.append(f"{name}: MISSING (was {old[:12]}...)")
            else:
                diffs.append(f"{name}: {old[:12]}... -> {digest[:12]}...")
    for pkg, ver in current["dependencies"].items():
        old = committed.get("dependencies", {}).get(pkg)
        if old is not None and old != ver:
            diffs.append(f"dependency {pkg}: {old} -> {ver}")
    return diffs


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--run", action="store_true", help="Re-run every experiment first (long)")
    ap.add_argument("--update", action="store_true",
                    help="Re-run and rewrite the manifest")
    args = ap.parse_args()

    if args.run or args.update:
        failed = run_experiments()
        if failed:
            raise SystemExit(f"\nExperiments failed: {', '.join(failed)}. "
                             "Not writing a manifest for a partial run.")

    manifest = build_manifest()

    print(f"\n{'=' * 70}\n  MANIFEST\n{'=' * 70}")
    print(f"  commit       {manifest['git']['commit'][:12]}"
          f"{'  (DIRTY TREE)' if manifest['git']['dirty'] else ''}")
    print(f"  python       {manifest['environment']['python']}  "
          f"{manifest['environment']['machine']}")
    for name, digest in manifest["files"].items():
        print(f"  {name:<38} {digest[:16] + '...' if digest else 'MISSING'}")
    print(f"\n  manifest hash  {manifest['manifest_hash']}")

    if manifest["git"]["dirty"]:
        print("\n  WARNING: the working tree is dirty, so the commit above does not "
              "describe what ran.")

    missing = [n for n, d in manifest["files"].items() if d is None]
    if missing:
        print(f"\n  {len(missing)} result file(s) missing. Run with --run to generate them.")

    if args.update:
        MANIFEST_PATH.parent.mkdir(parents=True, exist_ok=True)
        MANIFEST_PATH.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
        print(f"\n  wrote {MANIFEST_PATH}")
        return

    if not MANIFEST_PATH.exists():
        print(f"\n  No committed manifest at {MANIFEST_PATH}. "
              "Create one with --update once the results are final.")
        return

    committed = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    diffs = compare(manifest, committed)

    if not diffs:
        print("\n  REPRODUCED: every result file matches the committed manifest.")
        return

    print(f"\n  DIVERGED from the committed manifest ({len(diffs)}):")
    for d in diffs:
        print(f"    - {d}")
    print("\n  Note that floating-point results can differ across BLAS builds and CPU\n"
          "  architectures even at a fixed seed. A mismatch means something changed, not\n"
          "  necessarily that a number was edited.")
    raise SystemExit(1)


if __name__ == "__main__":
    main()
